# Generated by Django 5.0.2 on 2025-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
    ]
